# Generated by Django 4.0.1 on 2022-01-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='Image Vision'),
        ),
    ]
