# Generated by Django 4.0.1 on 2022-01-25 04:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_vision', '0003_alter_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=cloudinary.models.CloudinaryField(blank=True, default='Image Vision', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
